### ISSUE TITLE
How should metadata be preprocessed?

### ISSUE THREAD

**Issue by localjo** [solidusjs/metadata#3]
Just want to start a discussion about this;

Some of this metadata realistically should be preprocessed further. For example, if `parameters.category` = `meet-and-greet` and `resources.photo.0.title` = `Awesome Photobomb` and we want the title `Awesome Photobomb | Meet and Greet | Photos` or similar, we need to manipulate `parameters.category`.

**Comment by pushred** [comment]
With https://github.com/solidusjs/metadata/commit/631a4ba9f6f944e6f5f18653359363d54c61a414 you can do this like so:

``` hbs
title: {{resources.photo.0.title}} | {{parameters.category}} | Photos
```

**Comment by localjo** [comment]
What if we need to convert something to title case like `some title` --> `Some Title` ?

**Comment by pushred** [comment]
You should do that with helpers in a custom tags template, or a preprocessor after the metadata object is inserted.
